version: "3.9"

services:
  db-auth-next:
    container_name: db-auth-next
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth-next
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
